In [2]:
import torch
from icecream import ic

Everything in pytorch is based on Tensor operations.
A tensor can have different dimensions
so it can be 1d, 2d, or even 3d and higher

scalar, vector, matrix, tensor

In [3]:
# torch.empty(size): uninitiallized
x = torch.empty(1)  # scalar
ic(x)
x = torch.empty(3)  # vector, 1D
ic(x)
x = torch.empty(2, 3)  # matrix, 2D
ic(x)
x = torch.empty(2, 2, 3)  # tensor, 3 dimensions
# x = torch.empty(2,2,2,3) # tensor, 4 dimensions
ic(x)

ic| x: tensor([0.])
ic| x: tensor([0., 0., 0.])
ic| x: tensor([[0., 0., 0.],
               [0., 0., 0.]])
ic| x: tensor([[[0., 0., 0.],
                [0., 0., 0.]],
       
               [[0., 0., 0.],
                [0., 0., 0.]]])


tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [4]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
ic(x)
ic(x.dim)
ic(x.shape)
x=x.view(-1,1)
ic(x.shape)

ic| x: tensor([[0.3756, 0.5946, 0.4614],
               [0.8629, 0.8451, 0.6223],
               [0.3468, 0.3086, 0.7890],
               [0.4587, 0.0944, 0.7890],
               [0.1625, 0.9321, 0.9804]])
ic| x.dim: <built-in method dim of Tensor object at 0x0000023AAE0D9860>
ic| x.shape: torch.Size([5, 3])
ic| x.shape: torch.Size([15, 1])


torch.Size([15, 1])

In [5]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
ic(x)

ic| x: tensor([[0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.]])


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# check size
ic(x.size())
ic(x.shape)
# check data type
ic(x.dtype)

ic| x.size(): torch.Size([5, 3])
ic| x.shape: torch.Size([5, 3])
ic| x.dtype: torch.float32


torch.float32

In [7]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
ic(x)

ic| x: tensor([[0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.]], dtype=torch.float16)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [8]:
# check type
ic(x.dtype)

ic| x.dtype: torch.float16


torch.float16

In [9]:
# construct from data
x = torch.tensor([5.5, 3])
ic(x.size())
ic(x.shape)

ic| x.size(): torch.Size([2])
ic| x.shape: torch.Size([2])


torch.Size([2])

In [10]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
ic(x)

ic| x: tensor([5.5000, 3.0000], requires_grad=True)


tensor([5.5000, 3.0000], requires_grad=True)

In [11]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)


In [12]:
# elementwise addition
z = x + y
# torch.add(x,y)

in place addition, everythin with a trailing underscore is an inplace operation
i.e. it will modify the variable
y.add_(x)

In [13]:
# substraction
z = x - y
z = torch.sub(x, y)

In [14]:
# multiplication
z = x * y
z = torch.mul(x, y)

In [15]:
# division
z = x / y
z = torch.div(x, y)

In [16]:
# Slicing
x = torch.rand(5, 3)
ic(x)
ic(x[:, 0])  # all rows, column 0
ic(x[1, :])  # row 1, all columns
ic(x[1, 1])  # element at 1, 1

ic| x: tensor([[0.9303, 0.5343, 0.2429],
               [0.2801, 0.1686, 0.3891],
               [0.8172, 0.3024, 0.6008],
               [0.3181, 0.4802, 0.9206],
               [0.7299, 0.5868, 0.3806]])
ic| x[:, 0]: tensor([0.9303, 0.2801, 0.8172, 0.3181, 0.7299])
ic| x[1, :]: tensor([0.2801, 0.1686, 0.3891])
ic| x[1, 1]: tensor(0.1686)


tensor(0.1686)

In [17]:
# Get the actual value if only 1 element in your tensor
ic(x[1, 1].item())

ic| x[1, 1].item(): 0.16856497526168823


0.16856497526168823

In [18]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
ic(x.size(), y.size(), z.size())

ic| x.size(): torch.Size([4, 4])
    y.size(): torch.Size([16])
    z.size(): torch.Size([2, 8])


(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [19]:
# create a 4-dim  tensor
a = torch.rand(4,3,28,28)
ic(a[0].shape)

# ... all
a[...].shape

ic| a[0].shape: torch.Size([3, 28, 28])


torch.Size([4, 3, 28, 28])

In [20]:
ic(a[0][0].shape)
ic(a[0,0,2,4])
# ic(a)
ic(a[:2].shape)
ic(a[:2,:1,:,:].shape)
ic(a.shape)

# select by steps
ic(a[:,:,0:28:2,0:28:2].shape)
ic(a[0,...].shape)


ic| a[0][0].shape: torch.Size([28, 28])
ic| a[0,0,2,4]: tensor(0.5984)
ic| a[:2].shape: torch.Size([2, 3, 28, 28])
ic| a[:2,:1,:,:].shape: torch.Size([2, 1, 28, 28])
ic| a.shape: torch.Size([4, 3, 28, 28])
ic| a[:,:,0:28:2,0:28:2].shape: torch.Size([4, 3, 14, 14])
ic| a[0,...].shape: torch.Size([3, 28, 28])


torch.Size([3, 28, 28])

In [21]:
x = torch.randn(3,4)
ic(x)
# select by mask
mask=x.ge(0.5)
ic(torch.masked_select(x,mask))

ic| x: tensor([[-1.2083, -1.3375, -0.8635, -0.0637],
               [ 0.2773, -0.0370,  0.2248,  0.4562],
               [ 1.2179,  0.0964, -0.7944, -1.6380]])
ic| torch.masked_select(x,mask): tensor([1.2179])


tensor([1.2179])

In [22]:
b= torch.tensor([[4,3,5],[9,7,8]])

# select by flatten index

ic(b)
ic((torch.take(b,torch.tensor([0,3,5]))))

ic| b: tensor([[4, 3, 5],
               [9, 7, 8]])
ic| torch.take(b,torch.tensor([0,3,5])): tensor([4, 9, 8])


tensor([4, 9, 8])

In [23]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
ic(a)

ic| a: tensor([1., 1., 1., 1., 1.])


tensor([1., 1., 1., 1., 1.])

In [24]:
# torch to numpy with .numpy()
b = a.numpy()
ic(b)
ic(type(b))

ic| b: array([1., 1., 1., 1., 1.], dtype=float32)
ic| type(b): <class 'numpy.ndarray'>


numpy.ndarray

In [25]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
ic(a)
ic(b)

ic| a: tensor([2., 2., 2., 2., 2.])
ic| b: array([2., 2., 2., 2., 2.], dtype=float32)


array([2., 2., 2., 2., 2.], dtype=float32)

In [26]:
# numpy to torch with .from_numpy(x)
import numpy as np

In [27]:
a = np.ones(5)
b = torch.from_numpy(a)
ic(a)
ic(b)

ic| a: array([1., 1., 1., 1., 1.])
ic| b: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [28]:
# again be careful when modifying
a += 1
ic(a)
ic(b)

ic| a: array([2., 2., 2., 2., 2.])
ic| b: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [8]:
import torch
 
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
 
result = torch.stack([a, b], 0)
print(result)
print(result.dim())
print(result.shape)




tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
torch.Size([2, 2, 2])


In [9]:
import torch
 
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
 
result = torch.stack([a, b], 1)
print(result)
print(result.dim)
print(result.shape)

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
<built-in method dim of Tensor object at 0x000002333EA91720>
torch.Size([2, 2, 2])


In [2]:
import torch
 
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
 
result = torch.stack([a, b], 2)
print(result)
print(result.dim)

tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])


In [29]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")  # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)  # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")  # ``.to`` can also change dtype together!
    # z = z.numpy()