In [49]:
import torch
from icecream import ic

Everything in pytorch is based on Tensor operations.
A tensor can have different dimensions
so it can be 1d, 2d, or even 3d and higher

scalar, vector, matrix, tensor

In [50]:
# torch.empty(size): uninitiallized
x = torch.empty(1)  # scalar
ic(x)
x = torch.empty(3)  # vector, 1D
ic(x)
x = torch.empty(2, 3)  # matrix, 2D
ic(x)
x = torch.empty(2, 2, 3)  # tensor, 3 dimensions
# x = torch.empty(2,2,2,3) # tensor, 4 dimensions
ic(x)

ic| x: tensor([1.0842e-19])
ic| x: tensor([-1.2630e-29,  1.0972e-42,  2.3694e-38])
ic| x: tensor([[-1.2823e-29,  1.0972e-42,  0.0000e+00],
               [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
ic| x: tensor([[[0., 0., 0.],
                [0., 0., 0.]],
       
               [[0., 0., 0.],
                [0., 0., 0.]]])


tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [51]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
ic(x)
ic(x.dim)
ic(x.shape)
x=x.view(-1,1)
ic(x.shape)

ic| x: tensor([[0.0032, 0.5716, 0.8747],
               [0.3204, 0.4877, 0.9229],
               [0.6943, 0.9788, 0.5719],
               [0.8311, 0.9558, 0.4234],
               [0.5475, 0.2182, 0.2137]])
ic| x.dim: <built-in method dim of Tensor object at 0x0000014BEDD679F0>
ic| x.shape: torch.Size([5, 3])
ic| x.shape: torch.Size([15, 1])


torch.Size([15, 1])

In [52]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
ic(x)

ic| x: tensor([[0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.]])


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [53]:
# check size
ic(x.size())
ic(x.shape)

ic| x.size(): torch.Size([5, 3])
ic| x.shape: torch.Size([5, 3])


torch.Size([5, 3])

In [54]:
# check data type
ic(x.dtype)

ic| x.dtype: torch.float32


torch.float32

In [55]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
ic(x)

ic| x: tensor([[0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.],
               [0., 0., 0.]], dtype=torch.float16)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [56]:
# check type
ic(x.dtype)

ic| x.dtype: torch.float16


torch.float16

In [57]:
# construct from data
x = torch.tensor([5.5, 3])
ic(x.size())

ic| x.size(): torch.Size([2])


torch.Size([2])

In [58]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)

In [59]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

In [60]:
# elementwise addition
z = x + y
# torch.add(x,y)

in place addition, everythin with a trailing underscore is an inplace operation
i.e. it will modify the variable
y.add_(x)

In [61]:
# substraction
z = x - y
z = torch.sub(x, y)

In [62]:
# multiplication
z = x * y
z = torch.mul(x, y)

In [63]:
# division
z = x / y
z = torch.div(x, y)

In [64]:
# Slicing
x = torch.rand(5, 3)
ic(x)
ic(x[:, 0])  # all rows, column 0
ic(x[1, :])  # row 1, all columns
ic(x[1, 1])  # element at 1, 1

ic| x: tensor([[0.6238, 0.0640, 0.2865],
               [0.7639, 0.3790, 0.8052],
               [0.8490, 0.7459, 0.3109],
               [0.1538, 0.1694, 0.0180],
               [0.4416, 0.4252, 0.0572]])
ic| x[:, 0]: tensor([0.6238, 0.7639, 0.8490, 0.1538, 0.4416])
ic| x[1, :]: tensor([0.7639, 0.3790, 0.8052])
ic| x[1, 1]: tensor(0.3790)


tensor(0.3790)

In [65]:
# Get the actual value if only 1 element in your tensor
ic(x[1, 1].item())

ic| x[1, 1].item(): 0.379009485244751


0.379009485244751

In [66]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
ic(x.size(), y.size(), z.size())

ic| x.size(): torch.Size([4, 4])
    y.size(): torch.Size([16])
    z.size(): torch.Size([2, 8])


(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [78]:
# create a 4-dim  tensor
a = torch.rand(4,3,28,28)
ic(a[0].shape)
a[...].shape

ic| a[0].shape: torch.Size([3, 28, 28])


torch.Size([4, 3, 28, 28])

In [80]:
ic(a[0][0].shape)
ic(a[0,0,2,4])
# ic(a)
ic(a[:2].shape)
ic(a[:2,:1,:,:].shape)
ic(a.shape)
ic(a[:,:,0:28:2,0:28:2].shape)
ic(a[0,...].shape)


ic| a[0][0].shape: torch.Size([28, 28])
ic| a[0,0,2,4]: tensor(0.3009)
ic| a[:2].shape: torch.Size([2, 3, 28, 28])
ic| a[:2,:1,:,:].shape: torch.Size([2, 1, 28, 28])
ic| a.shape: torch.Size([4, 3, 28, 28])
ic| a[:,:,0:28:2,0:28:2].shape: torch.Size([4, 3, 14, 14])
ic| a[0,...].shape: torch.Size([3, 28, 28])


torch.Size([3, 28, 28])

In [82]:
x = torch.randn(3,4)
ic(x)
mask=x.ge(0.5)
ic(torch.masked_select(x,mask))

ic| x: tensor([[-1.2493, -0.4753,  0.7201,  0.9010],
               [-0.0434, -1.0270, -0.8996, -0.1165],
               [-1.9691, -1.1417,  1.1260,  0.9683]])
ic| torch.masked_select(x,mask): tensor([0.7201, 0.9010, 1.1260, 0.9683])


tensor([0.7201, 0.9010, 1.1260, 0.9683])

In [88]:
### b= torch.tensor([[4,3,5],[9,7,8]])
ic(b)
ic((torch.take(b,torch.tensor([0,3,5]))))

ic| b: tensor([[4, 3, 5],
               [9, 7, 8]])
ic| torch.take(b,torch.tensor([0,3,5])): tensor([4, 9, 8])


tensor([4, 9, 8])

In [ ]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
ic(a)

In [ ]:
# torch to numpy with .numpy()
b = a.numpy()
ic(b)
ic(type(b))

In [ ]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
ic(a)
ic(b)

In [ ]:
# numpy to torch with .from_numpy(x)
import numpy as np

In [ ]:
a = np.ones(5)
b = torch.from_numpy(a)
ic(a)
ic(b)

In [ ]:
# again be careful when modifying
a += 1
ic(a)
ic(b)

In [ ]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")  # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)  # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")  # ``.to`` can also change dtype together!
    # z = z.numpy()