In [1]:
import torch
from icecream import ic

Everything in pytorch is based on Tensor operations.
A tensor can have different dimensions
so it can be 1d, 2d, or even 3d and higher

scalar, vector, matrix, tensor

In [2]:
# torch.empty(size): uninitiallized
x = torch.empty(1)  # scalar
ic(x)
x = torch.empty(3)  # vector, 1D
ic(x)
x = torch.empty(2, 3)  # matrix, 2D
ic(x)
x = torch.empty(2, 2, 3)  # tensor, 3 dimensions
# x = torch.empty(2,2,2,3) # tensor, 4 dimensions
ic(x)

ic| x: tensor([3.2329e-27])
ic| x: tensor([0., 0., 0.])
ic| x: tensor([[0., 0., 0.],
               [0., 0., 0.]])
ic| x: tensor([[[0., 0., 0.],
                [0., 0., 0.]],
       
               [[0., 0., 0.],
                [0., 0., 0.]]])


tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
ic(x)
ic(x.dim)
ic(x.shape)
x=x.view(-1,1)
ic(x.shape)

In [ ]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
ic(x)

In [ ]:
# check size
ic(x.size())
ic(x.shape)
# check data type
ic(x.dtype)

In [ ]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
ic(x)

In [ ]:
# check type
ic(x.dtype)

In [ ]:
# construct from data
x = torch.tensor([5.5, 3])
ic(x.size())
ic(x.shape)

In [ ]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
ic(x)

In [5]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)


In [6]:
# elementwise addition
z = x + y
# torch.add(x,y)

in place addition, everythin with a trailing underscore is an inplace operation
i.e. it will modify the variable
y.add_(x)

In [7]:
# substraction
z = x - y
z = torch.sub(x, y)

In [8]:
# multiplication
z = x * y
z = torch.mul(x, y)

In [9]:
# division
z = x / y
z = torch.div(x, y)

In [10]:
# Slicing
x = torch.rand(5, 3)
ic(x)
ic(x[:, 0])  # all rows, column 0
ic(x[1, :])  # row 1, all columns
ic(x[1, 1])  # element at 1, 1

ic| x: tensor([[0.6571, 0.4132, 0.9488],
               [0.5992, 0.2031, 0.0740],
               [0.9701, 0.4894, 0.2960],
               [0.7737, 0.2852, 0.7675],
               [0.1031, 0.6315, 0.0447]])
ic| x[:, 0]: tensor([0.6571, 0.5992, 0.9701, 0.7737, 0.1031])
ic| x[1, :]: tensor([0.5992, 0.2031, 0.0740])
ic| x[1, 1]: tensor(0.2031)


tensor(0.2031)

In [11]:
# Get the actual value if only 1 element in your tensor
ic(x[1, 1].item())

ic| x[1, 1].item(): 0.20311230421066284


0.20311230421066284

In [12]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
ic(x.size(), y.size(), z.size())

ic| x.size(): torch.Size([4, 4])
    y.size(): torch.Size([16])
    z.size(): torch.Size([2, 8])


(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [13]:
# create a 4-dim  tensor
a = torch.rand(4,3,28,28)
ic(a[0].shape)

# ... all
a[...].shape

ic| a[0].shape: torch.Size([3, 28, 28])


torch.Size([4, 3, 28, 28])

In [14]:
ic(a[0][0].shape)
ic(a[0,0,2,4])
# ic(a)
ic(a[:2].shape)
ic(a[:2,:1,:,:].shape)
ic(a.shape)

# select by steps
ic(a[:,:,0:28:2,0:28:2].shape)
ic(a[0,...].shape)


ic| a[0][0].shape: torch.Size([28, 28])
ic| a[0,0,2,4]: tensor(0.4558)
ic| a[:2].shape: torch.Size([2, 3, 28, 28])
ic| a[:2,:1,:,:].shape: torch.Size([2, 1, 28, 28])
ic| a.shape: torch.Size([4, 3, 28, 28])
ic| a[:,:,0:28:2,0:28:2].shape: torch.Size([4, 3, 14, 14])
ic| a[0,...].shape: torch.Size([3, 28, 28])


torch.Size([3, 28, 28])

In [15]:
x = torch.randn(3,4)
ic(x)
# select by mask
mask=x.ge(0.5)
ic(torch.masked_select(x,mask))

ic| x: tensor([[-0.1662, -0.8114, -3.0582,  1.6215],
               [-1.5722,  0.7286, -0.4503,  0.9735],
               [-0.7637,  0.2155,  2.6432, -0.4467]])
ic| torch.masked_select(x,mask): tensor([1.6215, 0.7286, 0.9735, 2.6432])


tensor([1.6215, 0.7286, 0.9735, 2.6432])

In [97]:
b= torch.tensor([[4,3,5],[9,7,8]])

# select by flatten index

ic(b)
ic((torch.take(b,torch.tensor([0,3,5]))))

ic| b: tensor([[4, 3, 5],
               [9, 7, 8]])
ic| torch.take(b,torch.tensor([0,3,5])): tensor([4, 9, 8])


tensor([4, 9, 8])

In [ ]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
ic(a)

In [ ]:
# torch to numpy with .numpy()
b = a.numpy()
ic(b)
ic(type(b))

In [ ]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
ic(a)
ic(b)

In [ ]:
# numpy to torch with .from_numpy(x)
import numpy as np

In [ ]:
a = np.ones(5)
b = torch.from_numpy(a)
ic(a)
ic(b)

In [ ]:
# again be careful when modifying
a += 1
ic(a)
ic(b)

In [ ]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")  # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)  # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")  # ``.to`` can also change dtype together!
    # z = z.numpy()